### ISSUE TITLE
Call to a member function setMethod() on a non-object

### ISSUE THREAD

**Issue by reddotcreative** [CKOTech/checkout-magento-plugin#1]
app/code/community/CheckoutApi/ChargePayment/etc/config.xml

There is a capital P within "config/global/blocks/checkoutapi_chargePayment/class" which causes the correct Block to not be loaded.

https://github.com/CKOTech/checkout-magento-plugin/commit/1118e32b5d738dc2cb1b5003e668622a932c151d

**Comment by dhiraj-gangoosirdar-cko** [comment]
@reddotcreative  the capital P won't cause an issue, it's just the name of he class group
CheckoutApi_ChargePayment_Block

**Comment by dhiraj-gangoosirdar-cko** [comment]
@reddotcreative  thank you for noticing this issue. The node checkoutapi_chargePayment usually is an
identifier in magento. As far as i know magento use this identifier to get

the class group in our case CheckoutAPi_ChargePayment_Block.

Can you please provide me the full log stack trace ?

**Comment by dhiraj-gangoosirdar-cko** [comment]
issue has been fixed
