### ISSUE TITLE
fatal error when creating a credit memo

### ISSUE THREAD

**Issue by ebaschiera** [CKOTech/checkout-magento-plugin#12]
Hi,
I'm getting the following error when creating a credit memo with refund online:
PHP Fatal error:  Undefined class constant 'STATUS_CAPTURE' in /home/www/lib/CheckoutApi/Client/ClientGW3.php on line 334
Apparently the file /lib/CheckoutApi/Client/Constant.php is missing the constant "STATUS_CAPTURE" with value "Captured".

Thanks.
-Ermanno Baschiera

**Comment by ravish-ramrakha-cko** [comment]
A fix is already available in the prerelease 2.2.2.
